### ISSUE TITLE
Spreadsheet Not loading.

### ISSUE THREAD

**Issue by barob1n** [netbrain/spreadsheet-js#2]
Installed PHPExcel and the Spreadsheet Extensions for MediaWiki.  Both extensions show up in the mediawiki version page, and appear to be installed correctly.  However,  spreadsheets do not load.  The page displays "Please wait, spreadsheet is loading".  Any help or suggestions will be appreciated.

Currently running:
Product        Version
MediaWiki     1.22.2
PHP               5.4.25 (apache2handler)
MySQL         5.5.36
PHPExcel       1.7.8
Spreasheet    .1

**Comment by netbrain** [comment]
Is your wiki publicly available? I could take a look.

**Comment by barob1n** [comment]
## Sorry.  It is currently only available on our local intranet. Any other suggestions?  

On Fri, 2/28/14, Kim Eik notifications@github.com wrote:

 Subject: Re: [spreadsheet-js] Spreadsheet Not loading. (#2)
 To: "netbrain/spreadsheet-js" spreadsheet-js@noreply.github.com
 Cc: "barob1n" barob1n@yahoo.com
 Date: Friday, February 28, 2014, 11:30 AM

 Is your wiki publicly available? I could
 take a look.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by netbrain** [comment]
Well, is there any javascript errors displayed in the browsers console? Which browser are you using?
Is there any exceptions thrown in mediawiki debug log?

**Comment by barob1n** [comment]
Thanks again for your help.  We've tried using IE and Chrome. The mediawiki debug log didn't show anything unusual.  However, using Chrome's debugger 
gives the following error:

/*
Internal error
*/
mw.loader.state({"spreadsheet.core":"missing"});

Thanks again
Brian

---

On Fri, 2/28/14, Kim Eik notifications@github.com wrote:

 Subject: Re: [spreadsheet-js] Spreadsheet Not loading. (#2)
 To: "netbrain/spreadsheet-js" spreadsheet-js@noreply.github.com
 Cc: "barob1n" barob1n@yahoo.com
 Date: Friday, February 28, 2014, 6:30 PM

 Well, is there any javascript errors
 displayed in the browsers console? Which browser are you
 using?

 Is there any exceptions thrown in mediawiki debug log?

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by netbrain** [comment]
when installing the extension did you run the command:
git submodule update --recursive --init

??

**Comment by barob1n** [comment]
## Thanks.  That was the problem.

On Tue, 3/4/14, Kim Eik notifications@github.com wrote:

 Subject: Re: [spreadsheet-js] Spreadsheet Not loading. (#2)
 To: "netbrain/spreadsheet-js" spreadsheet-js@noreply.github.com
 Cc: "barob1n" barob1n@yahoo.com
 Date: Tuesday, March 4, 2014, 2:10 PM

 when installing the extension did you
 run the commands:

 git submodule init

 and

 git submodule update --recursive --init

 ??

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by netbrain** [comment]
Sorry for the ackward installation, but its still really in early development so its to be expected. Next time please use the discussion tab on the extensions page instead of this project.
